[Main]
# 0 - OpenAI, 1 - Groq (Llama 3), 2 - OpenRouter (free models - https://openrouter.ai/models?q=%3Afree)
AIProvider=1

# https://platform.openai.com/account/api-keys
OpenAPIKey=sk-...

# https://console.groq.com/keys
GroqAPIKey=gsk_...

# https://openrouter.ai/settings/keys
OpenRouterAPIKey=sk-or-v1-...

# The history limit of 12,000 characters or 4,000 tokens (1 token 3 characters) is selected for Llama 3.3. Depending on the capabilities of the selected neural network, the number may change
# Выбрано ограничение истории в 12.000 символов или 4000 токенов (1 токен 3 символа) для Llama 3.3. В зависимости от возможностей выбранной нейросети число может измениться
HistoryLimit=12000

# https://t.me/botfather
TelegramToken=...

# The Telegram chat number is assigned automatically after the bot receives the first message if the FirstRun parameter is 1. You can find out the chat number by changing ShowMessages to 1.
# Номер чата Telegram присваивается автоматически после получения первого сообщения ботом, если параметр FirstRun равен 1. Узнать номер чата можно изменить ShowMessages на 1.
TelegramMasterChatID=0

# Only Groq AI provider / Нужно для обхода санкций
Proxy=

# In milliseconds, one second is 1000, and one minute is 60000 / В миллисекундах, одна секунда это 1000, а одна минута это 60000
SleepTimeOut=1000

DebugMode=0
ShowMessages=1
SendImages=1

# First launch, needed for automatic recording of the Telegram chat ID
# Первый запуск, нужен для автоматической записи номера Telegram чата
FirstRun=1