[Main]
# 0 - OpenAI, 1 - Groq (Llama 3)
AIProvider=0

# https://platform.openai.com/account/api-keys
OpenAPIKey=sk-...

# https://console.groq.com/keys
GroqAPIKey=gsk_...

# The history limit of 12,000 characters or 4,000 tokens (1 token 3 characters) is selected for Llama 3.1. Depending on the capabilities of the selected neural network, the number may change
# Выбрано ограничение истории в 12.000 символов или 4000 токенов (1 токен 3 символа) для Llama 3.1. В зависимости от возможностей выбранной нейросети число может измениться
HistoryLimit=12000

# https://t.me/botfather
TelegramToken=...

# Enter your telegram nick / Введите ваш телеграм ник
TelegramMasterUser=...

# Enter the chat number by looking in the console, after sending the message, after entering, remove the display of messages by changing ShowMessages to 0
# Введите номер чата посмотрев в консоли, после отправки сообщения, после ввода убрать вывод сообщений изменив ShowMessages на 0
TelegramMasterChatID=0

# Only Groq AI provider / Нужно для обхода санкций
Proxy=

SleepTimeOut=10

DebugMode=0
ShowMessages=1
SendImages=1
